# Generated by Django 5.1.7 on 2025-06-27 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreMateria", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeroSemestre", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreUsuario", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreProfesor", models.CharField(max_length=100)),
                (
                    "materiaQueDa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profesores",
                        to="profesores.materia",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="materia",
            name="semestreEnQueSeCursa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materias",
                to="profesores.semestre",
            ),
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField(blank=True)),
                ("calificacionClaridad", models.PositiveIntegerField()),
                ("calificacionExigencia", models.PositiveIntegerField()),
                ("calificacionApoyo", models.PositiveIntegerField()),
                ("recomienda", models.BooleanField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="profesores.profesor",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesores.usuario",
                    ),
                ),
            ],
        ),
    ]
