# Generated by Django 5.1.7 on 2025-06-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profesores", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comentario",
            old_name="calificacionApoyo",
            new_name="calificacionRespeto",
        ),
    ]
