# Generated by Django 5.1.7 on 2025-06-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profesores", "0002_rename_calificacionapoyo_comentario_calificacionrespeto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profesor",
            name="materiaQueDa",
        ),
        migrations.AddField(
            model_name="profesor",
            name="materiasQueDa",
            field=models.ManyToManyField(
                related_name="profesores", to="profesores.materia"
            ),
        ),
    ]
