# Generated by Django 5.1.7 on 2025-07-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profesores", "0003_remove_profesor_materiaqueda_profesor_materiasqueda"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="password",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
