# Generated by Django 5.1.7 on 2025-07-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profesores", "0004_usuario_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="password",
            field=models.CharField(max_length=10),
        ),
    ]
